services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isi_burger_app
    ports:
      - "8081:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=isi_burger
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - MAIL_MAILER=smtp
      - MAIL_HOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=823c99a0a24e26
      - MAIL_PASSWORD=e354b5c28d359b
      - MAIL_FROM_ADDRESS=no-reply@isiburger.com
      - MAIL_FROM_NAME=ISI BURGER
    depends_on:
      - db
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - isi_network

  db:
    image: mysql:8.0
    container_name: isi_burger_db
    environment:
      MYSQL_DATABASE: isi_burger
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - isi_network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: isi_burger_jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - isi_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: isi_burger_ngrok
    environment:
      - NGROK_AUTHTOKEN=3CCwklaXOEDAdIVT2kdbDwXY10N_2GNr9kRFWfNxymawza82y
    command: http jenkins:8080
    ports:
      - "4040:4040"
    depends_on:
      - jenkins
    networks:
      - isi_network

volumes:
  db_data:
  jenkins_data:

networks:
  isi_network:
    driver: bridge